### ISSUE TITLE
Where is XInputUSB?

### ISSUE THREAD

**Issue by LittleRainGames** [dmadison/ArduinoXInput#24]
Just trying to "reverse engineer" XInput for use with AVR in Atmel Studio, and I stumbled apon your library.

I'm looking over the code but I don't see where XInputUSB is defined(the class), its driving me nuts! Can you help me out man.

Reading XInputUSB_API.md, and it says something about this just being one part of it, the library part. 
So where is The Backend, and The USB API, am I missing something?
Does that mean the Backend, and USB API would be something like LUFA?

Thanks

Edit: Are we supposed to create XInputUSB on our own?

Edit2: Nevermind, its included with board files in another repo. The link is in the bottom of XInputUSB_API.md for anyone else wondering.

**Comment by dmadison** [comment]
It's also stated twice in the readme, in bold letters, that you need to use one of the linked boards packages in addition to the library.

The 'backend' includes all of the USB descriptors, endpoint allocation, and interrupt handling. The USB API is the class, described in [XInputUSB_API.md](../blob/master/extras/XInputUSB_API.md), for facilitating data transfer between the user-facing library (this repo) and the data passed over USB. The class definition itself exists in the board-specific repos because the methods differ depending on the board.

If you look at `USBCore.cpp` in the AVR repo you can find most of the commands for the USB setup. I also recommend reading [this post](http://www.partsnotincluded.com/reverse-engineering/understanding-the-xbox-360-wired-controllers-usb-data) where I reverse-engineered the USB descriptor and control surface packets.
