### ISSUE TITLE
USB Descriptors for Arduino Due and MKR family?

### ISSUE THREAD

**Issue by shejan0** [dmadison/ArduinoXInput#27]
As of current, none of the MKR family (Due, Zero, etc.) are not supported by the XInput library. I am assuming that the main library does not need to be edited. But that USB descriptors for the Native USB port can exist to mimic an Xbox 360 controller.

I recently picked up Due thinking it was supported since it had a specific Native USB that can be used to mimic the Keyboard and Mouse but since there are no descriptors, I cannot use it as an XInput device.

**Comment by dmadison** [comment]
That's correct, none of the SAMD boards are currently supported. Someone would need to modify the SAMD core to work with the library. This requires:

* Modifying the device and configuration descriptors to match the Xbox 360 wired controller
* Initializing the send/receive endpoints and interrupts
* Creating the XInputUSB API for interfacing with the library ([see the `XInputUSB_API.md` file, located in the 'extras' folder for reference](https://github.com/dmadison/ArduinoXInput/blob/master/extras/XInputUSB_API.md))

These changes are beyond what you can inject through the `PluggableUSB` API, which is why the library requires the standalone boards repositories.

I don't own any of the SAMD boards myself, and the Teensy and AVR implementations are enough for me. If you'd like to tackle the SAMD modifications yourself I'd be happy to link back to them.
