### ISSUE TITLE
Change recommended test app 

### ISSUE THREAD

**Issue by offalynne** [dmadison/ArduinoXInput#52]
html5gamepad.com has been loaded with sketchy adware and autoplay ads and is apparently advertising sale of scraped user data

suggest pointing users to https://greggman.github.io/html5-gamepad-test/ or https://apps.nektro.net/gamepad

**Comment by dmadison** [comment]
Thanks for the heads-up, that's unfortunate to hear.

Do you know of an alternatives that share the same user-friendly interface? Both of your suggested alternatives work but they lack the graphic that shows which inputs correspond to which axis/button on the controller. I think that's important since users are not working with physical controllers and it can help identify swapped or mis-assigned inputs.

Previously the README directed users towards [gamepadviewer.com](https://gamepadviewer.com/), which has a nice display of the controller but lacks the debug information from html5gamepad.

**Comment by offalynne** [comment]
In my opinion pointing to either of the above (along with gamepadviewer.com for visualizer if that actually is necessary) is much better than pointing traffic toward a site that is [a transparent data-gathering scheme](https://gamepad-tester.com/privacy):
> _For a better experience while using our Service, we may require you to provide us with certain personally identifiable information, including but not limited to your name, phone number, and postal address._

**Comment by dmadison** [comment]
As I said, I am more than happy to change the recommended testing link if you know of an alternative with the same feature set.
